### ISSUE TITLE
menampilkan base64 qrcode pada json

### ISSUE THREAD

**Issue by csmediasarana** [ilsyaa/velixs-md#2]
bagaimana cara menampilkan response untuk qrcode pada jsonnya ya?

**Comment by ilsyaa** [comment]
bisa di baca dokumentasinya ada 
https://github.com/ilsyaa/velixs-md#listener-usageexamples

`whatsapp.onQRUpdated(({ sessionId, qr }) => {
  console.log(qr);
});`

tinggal convert aja ke base64
